# frozen_string_literal: true

require 'fileutils'

module Crosspack
  module Builders
    # Generates a PKGBUILD for AUR from the same file layout as the deb/rpm
    # builders. `files` keys are paths *inside the extracted source archive*
    # (relative to "$srcdir/$pkgname-$pkgver"), values are destinations in
    # the package root.
    class Pkgbuild
      def self.generate(name:, version:, release:, pkgdesc:, depends:, arch:,
                        files:, symlinks: {}, executables: [], source:,
                        maintainer:, url: '', license: 'Proprietary', output:)
        content = render(
          name: name, version: version, release: release, pkgdesc: pkgdesc,
          depends: Array(depends), arch: Array(arch), files: files,
          symlinks: symlinks, executables: executables, source: Array(source),
          maintainer: maintainer, url: url, license: license
        )
        FileUtils.mkdir_p(File.dirname(output))
        File.write(output, content)
        output
      end

      def self.render(name:, version:, release:, pkgdesc:, depends:, arch:,
                      files:, symlinks:, executables:, source:, maintainer:,
                      url:, license:)
        depends_line = depends.map { |d| "'#{d}'" }.join(' ')
        source_line = source.map { |s| "'#{s}'" }.join(' ')
        srcbase = "$srcdir/$pkgname-$pkgver"
        escaped_desc = pkgdesc.gsub("'", %q{'\''})

        install_lines = files.map do |src, dst|
          mode = executables.include?(dst) ? '755' : '644'
          "  install -Dm#{mode} \"#{File.join(srcbase, src)}\" \"$pkgdir/#{dst}\""
        end
        link_lines = symlinks.map do |link, target|
          "  install -d \"$(dirname \"$pkgdir/#{File.dirname(link)}\")\"\n" \
            "  ln -s #{target} \"$pkgdir/#{link}\""
        end

        <<~PKGBUILD
          # Maintainer: #{maintainer}
          # Generated by crosspack — edit deps.yaml, not this file.
          pkgname=#{name}
          pkgver=#{version}
          pkgrel=#{release}
          pkgdesc='#{escaped_desc}'
          arch=(#{arch.join(' ')})
          url='#{url}'
          license=(#{license})
          depends=(#{depends_line})
          source=(#{source_line})
          sha256sums=('SKIP')

          package() {
          #{(install_lines + link_lines).join("\n")}
          }
        PKGBUILD
      end
    end
  end
end
