# frozen_string_literal: true

require 'fileutils'
require 'open3'
require 'digest'

module Crosspack
  module Builders
    # Windows MSI packaging via the WiX toolset (wixtoolset.org). WiX v4+
    # runs on Linux as a .NET tool, so real MSI builds are possible once
    # `dotnet tool install -g wix` is available. Without it we still emit a
    # complete .wxs source plus build instructions — packaging is not blocked
    # by the toolchain.
    class Wix
      # MSI ProductVersion only honours three numeric fields (x.y.z).
      def self.msi_version(version)
        fields = version.to_s.split(/[.-]/).first(3)
        fields << '0' while fields.size < 3
        fields.map { |f| f.gsub(/\D/, '').empty? ? '0' : f.gsub(/\D/, '') }.join('.')
      end

      # Deterministic UpgradeCode derived from the package name, so upgrades
      # chain across releases without a hand-maintained GUID.
      def self.upgrade_code(name)
        digest = Digest::SHA1.hexdigest("crosspack:#{name}")
        hex = digest[0, 32].upcase
        "#{hex[0, 8]}-#{hex[8, 4]}-#{hex[12, 4]}-#{hex[16, 4]}-#{hex[20, 12]}"
      end

      def self.generate_wxs(name:, version:, manufacturer:, summary:, files:,
                            arch: 'x64')
        directory = arch == 'arm64' ? 'ProgramFiles6432Folder' : 'ProgramFiles64Folder'
        components = files.values.each_with_index.map do |dst, i|
          src = files.key(dst).gsub('/', '\\')
          "      <Component Id=\"c#{i}\" Guid=\"*\">\n" \
            "        <File Id=\"f#{i}\" Source=\"#{src}\" />\n" \
            '      </Component>'
        end.join("\n")

        <<~WXS
          <?xml version="1.0" encoding="UTF-8"?>
          <!-- Generated by crosspack. Build with: wix build -arch #{arch} -o #{name}.msi #{name}.wxs -->
          <Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
            <Package Name="#{name}" Manufacturer="#{manufacturer}" Version="#{msi_version(version)}"
                     UpgradeCode="{#{upgrade_code(name)}}" Scope="perMachine">
              <SummaryInformation Description="#{summary}" />
              <MajorUpgrade DowngradeErrorMessage="A newer version of #{name} is already installed." />

              <StandardDirectory Id="#{directory}">
                <Directory Id="INSTALLDIR" Name="#{name}" />
              </StandardDirectory>

              <Feature Id="Main" Title="#{name}" Level="1">
                <ComponentGroupRef Id="Payload" />
              </Feature>
            </Package>

            <Fragment>
              <ComponentGroup Id="Payload">
          #{components}
              </ComponentGroup>
            </Fragment>
          </Wix>
        WXS
      end

      # Writes the .wxs next to the output and, when WiX is installed,
      # builds a real MSI. Returns the path of whatever was produced.
      def self.build(name:, version:, manufacturer:, summary:, files:, output:,
                     arch: 'x64')
        arch = { 'x86_64' => 'x64', 'aarch64' => 'arm64' }.fetch(arch, arch)
        missing = files.reject { |src, _dst| File.file?(src) }
        unless missing.empty?
          details = missing.map { |src, dst| "  ✗ #{src} (for #{dst})" }.join("\n")
          raise BuildError,
                "Source files for packing not found:\n#{details}\n" \
                'Build the application for the target platform first.'
        end

        out_dir = File.dirname(output)
        FileUtils.mkdir_p(out_dir)
        wxs_path = File.join(out_dir, "#{name}.wxs")
        File.write(wxs_path, generate_wxs(name: name, version: version,
                                          manufacturer: manufacturer,
                                          summary: summary, files: files,
                                          arch: arch))

        wix = wix_command
        unless wix
          File.write(File.join(out_dir, 'BUILD-MSI.txt'), <<~TXT)
            MSI not built: WiX toolset not found in PATH.
            Install the .NET SDK and WiX:
              dotnet tool install -g wix
            Then build with:
              wix build -arch #{arch} -o #{File.basename(output)} #{name}.wxs
          TXT
          return wxs_path
        end

        out, status = Open3.capture2e(wix, 'build', "-arch #{arch}",
                                      '-o', output, wxs_path)
        unless status.success?
          raise BuildError, "wix build failed to build #{output}:\n#{out}"
        end
        output
      end

      def self.wix_command
        %w[wix dotnet].each do |cmd|
          _, _, status = Open3.capture3(cmd, '--version')
          return cmd if status.success?
        end
        nil
      rescue Errno::ENOENT
        nil
      end
    end
  end
end
