# frozen_string_literal: true

require 'fileutils'
require 'open3'
require 'digest'

module Crosspack
  module Builders
    # Windows MSI packaging via the WiX toolset (wixtoolset.org). WiX v4+
    # runs on Linux as a .NET tool, so real MSI builds are possible once
    # `dotnet tool install -g wix` is available. Without it we still emit a
    # complete .wxs source plus build instructions — packaging is not blocked
    # by the toolchain.
    class Wix
      # The UI extension providing the standard install wizard dialogs.
      UI_EXTENSION = 'WixToolset.UI.wixext'
      # WiX v6 cannot use the unpinned extension (it pulls the incompatible
      # 7.0.0, WIX6101 wixext7); 7+ resolves a matching version on its own.
      UI_EXTENSION_V6_PIN = "#{UI_EXTENSION}/6.0.1"

      # MSI ProductVersion honours three numeric fields (x.y.z), each 0..255:
      # a calver year (2026) would trip WIX1148, so it maps to the short
      # form (26) and leading zeros are dropped (2026.09.26 -> 26.9.26).
      def self.msi_version(version)
        fields = version.to_s.split(/[.-]/).first(3)
        fields << '0' while fields.size < 3
        fields.map do |f|
          n = f.to_i
          n %= 100 if n > 255
          n.to_s
        end.join('.')
      end

      # Deterministic UpgradeCode derived from the package name, so upgrades
      # chain across releases without a hand-maintained GUID.
      def self.upgrade_code(name)
        digest = Digest::SHA1.hexdigest("crosspack:#{name}")
        hex = digest[0, 32].upcase
        "#{hex[0, 8]}-#{hex[8, 4]}-#{hex[12, 4]}-#{hex[16, 4]}-#{hex[20, 12]}"
      end

      # Escapes XML entities so manifest values never break the generated .wxs.
      def self.escape(text)
        text.to_s.gsub('&', '&amp;').gsub('<', '&lt;').gsub('>', '&gt;').gsub('"', '&quot;')
      end

      # The deb-style "Name <email>" maintainer must not reach the MSI
      # Manufacturer property: it lands in ARP/Publisher (and an angle-bracket
      # email is invalid in Windows Installer paths), so only the name half
      # is kept.
      def self.sanitize_manufacturer(manufacturer)
        name = manufacturer.to_s.sub(/\s*<[^<>]*>\s*/, '').strip
        name.empty? ? manufacturer.to_s.delete('<>') : name
      end

      # Minimal RTF for the WixUI_InstallDir license dialog — it requires
      # WixUILicenseRtf to point at a real .rtf file, else the build fails.
      def self.license_rtf(text)
        escaped = text.to_s.gsub('\\', '\\\\\\\\').gsub('{', '\\{').gsub('}', '\\}')
        lines = escaped.lines.map(&:chomp)
        lines = [''] if lines.empty?
        "{\\rtf1\\ansi\n#{lines.join("\\par\n")}\n}\n"
      end

      # shortcuts: nil, or { name: "Display Name", target: "app.exe" } (the
      # payload file inside INSTALLFOLDER the shortcuts launch) — installs
      # Start Menu and Desktop shortcuts. icon: local path to an .ico for
      # the Add/Remove Programs entry (ARPPRODUCTICON), or nil.
      def self.generate_wxs(name:, version:, manufacturer:, summary:, files:,
                            arch: 'x64', shortcuts: nil, icon: nil)
        license_rtf_file = "#{name}-license.rtf"
        name = escape(name)
        manufacturer = escape(sanitize_manufacturer(manufacturer))
        summary = escape(summary)
        directory = arch == 'arm64' ? 'ProgramFiles6432Folder' : 'ProgramFiles64Folder'
        components = files.values.each_with_index.map do |dst, i|
          src = escape(files.key(dst).gsub('/', '\\'))
          "      <Component Id=\"c#{i}\" Guid=\"*\">\n" \
            "        <File Id=\"f#{i}\" Source=\"#{src}\" />\n" \
            '      </Component>'
        end.join("\n")

        # Id must be INSTALLFOLDER: WiX v4+ auto-creates a directory with
        # this exact Id (named "[Manufacturer] [ProductName]") only when the
        # author has not defined one; a different Id makes it add a phantom
        # sibling directory and Manufacturer leaks into install paths.
        shortcut_xml = shortcuts ? shortcuts_fragment(shortcuts) : nil
        feature_refs = ["<ComponentGroupRef Id=\"Payload\" />"]
        feature_refs << '<ComponentGroupRef Id="Shortcuts" />' if shortcuts
        arp_icon = icon ? arp_icon_fragment(icon) : nil

        <<~WXS
          <?xml version="1.0" encoding="UTF-8"?>
          <!-- Generated by crosspack. Build with: wix build -arch #{arch} -ext #{UI_EXTENSION} -o #{name}.msi #{name}.wxs -->
          <Wix xmlns="http://wixtoolset.org/schemas/v4/wxs"
               xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">
            <Package Name="#{name}" Manufacturer="#{manufacturer}" Version="#{msi_version(version)}"
                     UpgradeCode="{#{upgrade_code(name)}}" Scope="perMachine">
              <SummaryInformation Description="#{summary}" />
              <MajorUpgrade DowngradeErrorMessage="A newer version of #{name} is already installed." />

              <StandardDirectory Id="#{directory}">
                <Directory Id="INSTALLFOLDER" Name="#{name}" />
              </StandardDirectory>

              <Property Id="WixUILicenseRtf" Value="#{license_rtf_file}" />
              <ui:WixUI Id="WixUI_InstallDir" InstallDirectory="INSTALLFOLDER" />
          #{arp_icon}
              <Feature Id="Main" Title="#{name}" Level="1">
          #{feature_refs.map { |r| "        #{r}" }.join("\n")}
              </Feature>
            </Package>

            <Fragment>
              <ComponentGroup Id="Payload">
          #{components}
              </ComponentGroup>
            </Fragment>
          #{shortcut_xml}
          </Wix>
        WXS
      end

      # Start Menu + Desktop shortcuts for the main executable. The shortcut
      # component's KeyPath is a marker registry value (a shortcut cannot be
      # a KeyPath itself); the icon comes from the exe.
      def self.shortcuts_fragment(shortcuts)
        name = escape(shortcuts[:name])
        target = escape(shortcuts[:target])
        <<~XML
          <Fragment>
            <ComponentGroup Id="Shortcuts" Directory="INSTALLFOLDER">
              <Component Id="c.shortcuts" Guid="*">
                <Shortcut Id="StartMenuShortcut" Directory="ProgramMenuFolder"
                          Name="#{name}" Target="[INSTALLFOLDER]#{target}"
                          WorkingDirectory="INSTALLFOLDER" />
                <Shortcut Id="DesktopShortcut" Directory="DesktopFolder"
                          Name="#{name}" Target="[INSTALLFOLDER]#{target}"
                          WorkingDirectory="INSTALLFOLDER" />
                <RegistryValue Root="HKLM" Key="Software\\#{name}"
                               Name="installed" Type="integer" Value="1" KeyPath="yes" />
              </Component>
            </ComponentGroup>
          </Fragment>
        XML
      end

      # Writes the .wxs (plus the license .rtf the UI wizard shows) next to
      # the output and, when WiX is installed, builds a real MSI. Returns
      # the path of whatever was produced.
      def self.build(name:, version:, manufacturer:, summary:, files:, output:,
                     arch: 'x64', shortcuts: nil, license: nil, icon: nil)
        arch = { 'x86_64' => 'x64', 'aarch64' => 'arm64' }.fetch(arch, arch)
        missing = files.reject { |src, _dst| File.file?(src) }
        unless missing.empty?
          details = missing.map { |src, dst| "  ✗ #{src} (for #{dst})" }.join("\n")
          raise BuildError,
                "Source files for packing not found:\n#{details}\n" \
                'Build the application for the target platform first.'
        end

        out_dir = File.dirname(output)
        FileUtils.mkdir_p(out_dir)
        wxs_path = File.join(out_dir, "#{name}.wxs")
        File.write(wxs_path, generate_wxs(name: name, version: version,
                                          manufacturer: manufacturer,
                                          summary: summary, files: files,
                                          arch: arch, shortcuts: shortcuts,
                                          icon: icon))
        File.write(File.join(out_dir, "#{name}-license.rtf"),
                   license_rtf(license || summary))
        FileUtils.cp(icon, File.join(out_dir, File.basename(icon))) if icon

        wix = wix_command
        unless wix
          File.write(File.join(out_dir, 'BUILD-MSI.txt'), <<~TXT)
            MSI not built: WiX toolset not found in PATH.
            Install the .NET SDK and WiX:
              dotnet tool install -g wix
            The install wizard needs the UI extension:
              wix extension add -g #{UI_EXTENSION_V6_PIN}   # WiX 6.x (no pin needed for WiX 7+)
            Then build with:
              wix build -arch #{arch} -ext #{UI_EXTENSION} -o #{File.basename(output)} #{name}.wxs
          TXT
          return wxs_path
        end

        ensure_ui_extension(wix)
        out, status = Open3.capture2e(wix, 'build', '-arch', arch.to_s,
                                      '-ext', UI_EXTENSION,
                                      '-o', output, wxs_path)
        unless status.success?
          raise BuildError, "wix build failed to build #{output}:\n#{out}"
        end
        output
      end

      # WiX v4+ is a .NET tool invoked as `wix` (dotnet tool install -g wix);
      # plain `dotnet` cannot build an MSI, so it is not a fallback.
      def self.wix_command
        _, _, status = Open3.capture3('wix', '--version')
        return 'wix' if status.success?

        nil
      rescue Errno::ENOENT
        nil
      end

      # The Add/Remove Programs entry shows this icon (ARP/Publisher uses
      # the MSI Icons table, not the installed files).
      def self.arp_icon_fragment(icon)
        icon_file = File.basename(icon)
        "    <Property Id=\"ARPPRODUCTICON\" Value=\"AppIcon\" />\n" \
          "    <Icon Id=\"AppIcon\" SourceFile=\"#{escape(icon_file)}\" />"
      end

      # The WixUI dialogs live in the UI extension, so it must be installed
      # before `wix build -ext WixToolset.UI.wixext` can resolve it. A no-op
      # when it is already present.
      def self.ensure_ui_extension(wix = 'wix')
        list, = Open3.capture2e(wix, 'extension', 'list', '-g')
        return if list.include?(UI_EXTENSION)

        version, = Open3.capture2e(wix, '--version')
        spec = version.to_i >= 7 ? UI_EXTENSION : UI_EXTENSION_V6_PIN
        out, status = Open3.capture2e(wix, 'extension', 'add', '-g', spec)
        return if status.success?

        raise BuildError, "cannot install the WiX UI extension (#{spec}):\n#{out}"
      end
    end
  end
end
